recogition_eval:
  metrics:
    - Edit_dist
    - BLEU
  dataset:
    dataset_name: omnidocbench_single_module_dataset
    ground_truth:
      data_path: ./test/model_outputs/drawings_text_ocr.json
      data_key: text
    prediction:
      data_key: pred
    category_type: text