recogition_eval:  # Table
  metrics:
    - TEDS
    - Edit_dist
  dataset:
    dataset_name: omnidocbench_single_module_dataset
    ground_truth:
      data_path: ./test/model_outputs/drawings_table.json
      data_key: html
      category_filter: table
    prediction:
      data_key: pred
    category_type: table
